### ISSUE TITLE
bug?: When the preact-render-to-string dependency does not exist, the error that occurs is vague

### ISSUE THREAD

**Issue by rxliuli** [preactjs/preset-vite#101]
I used depcheck to identify and remove unused dependencies, among which `preact-render-to-string` was also deleted. I didn't realize that it is essential for prerender. However, I encountered a very strange error. Perhaps it's a good idea to add a check to see if this dependency exists when `prerender.enable === true` and throw a more explicit exception.

```ts
[preact:prerender] d is not a function
✓ built in 130ms
error during build:
TypeError: d is not a function
```

Reproducible Example 

```sh
git clone https://github.com/rxliuli/preact-ssg-demo.git
cd preact-ssg-demo
pnpm i
pnpm build
```

**Comment by rschristian** [comment]
That doesn't come from us, but your usage.

`preact-render-to-string` is an optional dependency of `preact-iso`, who's `prerender` function you're using in your demo. However, that's entirely provided by you, you control the prerendering method and we simply call the function you provide. Nothing about our implementation actually relies on RTS at all.

Take the following (completely valid) example:

```js
export async function prerender(data) {
	return { html: '<h1>Hello World!</h1>'
}
```

I agree that message isn't clear, but it might be better in Vite's repo.

**Comment by rxliuli** [comment]
I brought up this issue in the vitejs discussion forum to see what the vitejs community has to say.
https://github.com/vitejs/vite/discussions/15725

**Comment by rschristian** [comment]
Going to close this out as it looks like it's being properly addressed in Vite itself -- certainly feel free to comment if there's something we need to do here. Happy to reopen and investigate further.
