### ISSUE TITLE
Possibly flesh out prerender `fetch` patch with `ok`, `status`, etc.

### ISSUE THREAD

**Issue by rschristian** [preactjs/preset-vite#103]
Just ran into this on `www`, we check [`response.ok`](https://github.com/preactjs/preact-www/blob/4b02625a45b95af2e3845a4510eebfb040177bc1/src/lib/content.js#L22-L29) but the patched fetch here only provides [`{ text, json}`](https://github.com/preactjs/preset-vite/blob/a325c1f3811900f70277424304c9eb42fc60f8a7/src/prerender.ts#L180) in the response.

There are of course workarounds, ~~and we probably can't / wouldn't want to mock out everything~~, but it might be worth considering the following:
  - adding some static `ok: true, status: 200` etc. props to the return object
  - calling `readFile` ahead of time, properly returning 404's, etc.

Tbf, only really going to be an issue seen in existing projects.

**Comment by marvinhagemeister** [comment]
FYI: These days there is the `Response` constructor, so we should be able to do `new Response(content, init)` which has all the properties. So instead of stubbing a response we could construct a real one ourselves.

**Comment by rschristian** [comment]
Yup, that's what I was thinking with the second option if that wasn't clear.
