### ISSUE TITLE
`TypeError: <default export> is not a function` when using `"type": "module"`

### ISSUE THREAD

**Issue by rschristian** [preactjs/preset-vite#11]
Currently setting up Vite's ESM SSR output when I ran across this. 

`vite.config.js` I believe always loads externals via `require()` for the moment. Not sure if that's fixable using plain `tsc`, but worst case scenario the CJS exports just need a little rewrite at build time.

Side note: Man is that a bizarre way of doing things. You can "use" `import`, but not really.

**Comment by marvinhagemeister** [comment]
`vite.config.js` is internally transpiled via esbuild by vite and it rewrites all import statements to commonjs. The SSR output assumes a commonjs enviornment too: https://github.com/vitejs/vite/blob/e641d8e2970edf925ff1ef69fb0b24d5f5e22f05/packages/vite/src/node/ssr/ssrModuleLoader.ts#L93 . I'm not sure if there is anything we can do about that on the preset side. It seems like making vite aware of an ESM environment should be done in vite.

**Comment by rschristian** [comment]
Oh sure, but hopefully this will change that: https://github.com/vitejs/vite/pull/2157

And I'm not going to argue that this isn't silly, but changing the CJS export to 

```
module.exports = preactPlugin;
preactPlugin["default"] = preactPlugin;
```

would get the job done. It's what they do for the react-refresh plugin.

**Comment by marvinhagemeister** [comment]
Ohh I get it now. I was under the impression that the framework preact could not be found during SSR. Wasn't aware that you were referring to the preset itself. We should be able to do something about that.

**Comment by rschristian** [comment]
Oops, sorry! Could've written that a lot clearer now that I realize how vague that is, and how it also depends on using that as the name for the default import. Totally blanked there, my bad!
