### ISSUE TITLE
Error when updating to v2.8.2

### ISSUE THREAD

**Issue by tomosterlund** [preactjs/preset-vite#115]
Hey there. Thanks for this plugin :) 

I wanted to update to v2.8.2, but my test pipeline keeps failing with the following error message:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/schedule-x/schedule-x/node_modules/stack-trace/index.js from /home/runner/work/schedule-x/schedule-x/node_modules/@preact/preset-vite/dist/cjs/prerender.js not supported.
```

Here the full logs: https://github.com/schedule-x/schedule-x/actions/runs/8322035817/job/22769189509?pr=297

It suggests that I should use a dynamic import instead of a `require` statement. Only thing is: this does not make sense for my setup. I'm using ESM and am importing `@preact/preset-vite` as an ES module.

**Comment by rschristian** [comment]
What version were you on prior?

**Comment by rschristian** [comment]
You'll need to either add `"type": "module"` [here](https://github.com/schedule-x/schedule-x/blob/main/packages/shared/package.json) or convert [this](https://github.com/schedule-x/schedule-x/blob/main/packages/shared/src/config/e2e.vite.ts) to be `e2e.vite.mts`

Without it, that's CJS.

**Comment by tomosterlund** [comment]
You're right, thanks a lot. This worked perfectly :) I would say error is on my end then too.

This resolves it for me. Do you want the issue open still if something is broken in the CJS build?

**Comment by rschristian** [comment]
Let's keep it open, our CJS build is busted.

It's not a problem on your end necessarily, you're just not consuming our ESM build is all. Even if you intended to have an ESM config, we're shipping something that doesn't work in a target we're meant to be supporting, so mistake is on our end even if you can work around it.
