### ISSUE TITLE
Preact+Vite JS transforms cause code to break

### ISSUE THREAD

**Issue by trusktr** [preactjs/preset-vite#119]
How do we disable JS transforms? I have code that works fine in plain JS (no build). When I add Preact+Vite, the code is transformed into code for old browsers, and it breaks in strange ways (private fields, etc, are compiled to something for old browsers).

It looks like Preact's Vite plugin hard codes transforms, and it is not configurable:

https://github.com/preactjs/preset-vite/blob/aef0301bcf1f02ebc44433da331469d2ac70d99a/src/index.ts#L178-L185

So it is impossible to disable private fields, etc, from being compiled.

All I want is the JSX transform, nothing else.

**Comment by rschristian** [comment]
> All I want is the JSX transform, nothing else.

Simplest solution for now would be to add the following to your Vite config and forgo the JSX plugin we ship:

```js
export default defineConfig({
    build: {
        esbuild: {
            jsx: "automatic",
            jsxImportSource: "preact",
        }
    }
});
```

**Comment by trusktr** [comment]
I'm not sure what is exactly causing the issue, but I see stuff like `__privateGet` and `__privateSet` everywhere instead of private fields, etc. Basically the code is far-removed from what I wrote, and something is breaking it.

I tried your last tip to use `jsx:automatic` in the app I made with `npm init preact` after removing the preact preset, but I get

```
Uncaught ReferenceError: React is not defined
```

and the compiled code has `React.createElement` in it. Do I need a newer Vite than the one create-preact-app has?

**Comment by rschristian** [comment]
> I'm not sure what is exactly causing the issue, but I see stuff like __privateGet and __privateSet everywhere instead of private fields, etc.

Have you altered Vite's targets? Vite's default targets should be: `'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14'`. [Docs](https://vitejs.dev/config/build-options#build-target).

> I tried your last tip to use jsx:automatic in the app I made with npm init preact after removing the preact preset, but I get

Whoops, my bad. This is what you want:

```js
export default defineConfig({
    esbuild: {
        jsx: "automatic",
        jsxImportSource: "preact",
    }
});
```

**Comment by trusktr** [comment]
> Whoops, my bad. This is what you want:

Ah, thanks! I do get the same error (without Preact Vite preset). I suppose this issue can be closed because it isn't due to the Preact Vite preset.

> Have you altered Vite's targets?

Here's vite.config.js:

```js
import {defineConfig} from 'vite'

export default defineConfig({
	build: {
		target: 'esnext',
	},
	esbuild: {
		jsx: 'automatic',
		jsxImportSource: 'preact',
	},
})
```


Here's jsconfig.json:

```js
{
	"compilerOptions": {
		"target": "ES2022",
		"module": "ESNext",
		"moduleResolution": "bundler",
		"noEmit": true,
		"allowJs": true,
		"checkJs": false,

		/* Preact Config */
		"skipLibCheck": true
	},
	"include": ["node_modules/vite/client.d.ts", "**/*"]
}
```

I also tried `build.target=es2023` but I still get compiled code like this:

```js
        __privateSet(this, _task, Motor.addRenderTask((_t, dt) => {
          const dx2 = __privateGet(this, _targetX) - this._x;
          const dy2 = __privateGet(this, _targetY) - this._y;
          const fpsRatio = dt / 16.6666;
```

**Comment by rschristian** [comment]
> Ah, thanks! I do get the same error (without Preact Vite preset).

The `React is not defined` error? Strange, are you using a React node module? If so, you will need to set up aliasing too, which is another [fairly simple copy/paste](https://github.com/preactjs/preset-vite/blob/aef0301bcf1f02ebc44433da331469d2ac70d99a/src/index.ts#L235-L241).

> I also tried build.target=es2023 but I still get compiled code like this:

Is this after `vite build`, or are you checking the output in dev? If dev, you'll need to use `--force` to get Vite to re-precompile the module -- it'll do it once and then never again, leaving you with outdated results. If after a build, that's odd though. This is my test:

> src/index.js
```js
class Foo {
    #bar = 'baz';
    getBar() {
        return this.#bar;
    }   
}

export function App() {
    const foo = new Foo();
    console.log(foo.getBar());
    return (...)
}
```

> dist/assets/index-<hash>.js (prettified)
```js
class he{
    #e="baz";
    getBar(){
        return this.#e
    }
}
```

**Comment by trusktr** [comment]
> The `React is not defined` error? 

Sorry no, I mean the same build output causing the same error with my JS code (Preact JSX is fine now (like it was with the preset I imagine)).

> Is this after vite build, or are you checking the output in dev?

I was running `vite`, then looking at the code in browser devtools. I tried `vite --force` but no luck.

I managed to reproduce it here based on your blitz:

https://stackblitz.com/edit/vitejs-vite-mykqek?file=package.json,src%2Fmain.jsx,vite.config.js,src%2Fstyle.css,public%2Fvite.svg

When you try scrolling in the 3D scene, the error happened in console. If you click on this part of the stack:

<img width="603" alt="Screenshot 2024-05-14 at 2 52 45 PM" src="https://github.com/preactjs/preset-vite/assets/297678/b1935c26-a502-40a7-a78f-4d3513d2ef28">

You'll see the transpiled code with `__privateGet` like the one I pasted above.

**Comment by trusktr** [comment]
In the stackblitz, if you run `cat node_modules/lume/dist/interaction/ScrollFling.js` you can see the original source has original private fields.

**Comment by trusktr** [comment]
Not sure why the transpile is happening, but I wanted to eliminate that out of the question to see what's causing the error.

**Comment by trusktr** [comment]
Will close this since there's no issue with the Preact preset. Thanks for all the help!

**Comment by rschristian** [comment]
So this feels like a foot cannon to me, but apparently Vite lets you configure prebundling targets separately? I have no idea why anyone would want this.

```js
export default defineConfig({
    build: {
        target: 'esnext'
    },
    optimizeDeps: {
        esbuildOptions: {
             target: 'esnext'
        }
    },
    plugins: [preact()]
});
```

This should fix your class fields in dev (make sure you use `--force` to get Vite to recompile), however, there seems to still be some issues.

**Comment by trusktr** [comment]
Awesome, that does prevent all the extra build stuff, but the same error happens. So that's not the issue.

Blitz: https://stackblitz.com/edit/vitejs-vite-jqjrsr?file=main.jsx,vite.config.js

Is Preact modifying the environment in any way, f.e. modifying or intercepting DOM events, or patching globals?

So far I've used Lume with plain HTML, plain JS, Vue, Svelte, React, Lit, and Lume Element without this issue. This is my first Preact attempt, and the issue is popping up.

**Comment by rschristian** [comment]
>  Is Preact modifying the environment in any way, f.e. modifying or intercepting DOM events, or patching globals?

Hey we're _Preact_, not _React_!

> What I'm seeing is JS properties on the elements have string values on them from attributes set in Preact.

Can you be a bit more specific? You can't specifically set attrs or properties w/ Preact (or React, for that matter). Which gets set is an implementation detail really.

**Comment by trusktr** [comment]
> Hey we're _Preact_, not _React_!

Haha, noted.

> Can you be a bit more specific?


The value from `distance="301"` (in that blitz example's JSX) somehow ends up as a string on the element's `.distance` JS property. Normally Lume elements should be able to accept string values and handle them (that's how all the HTML attributes work, as they're mapped to JS properties).

Not sure what's going on, maybe something regressed in Lume. I'll keep investigating. Thanks for the help!

**Comment by rschristian** [comment]
> (that's how all the HTML attributes work, as they're mapped to JS properties).

Just to be clear, what are you expecting here? That the property gets set, or the attribute?

Preact will only set the property, not the attribute, and they are different things (`el.getAttribute('distance')` vs `el.distance`). Many (most?) properties do not reflect to attributes.

**Comment by trusktr** [comment]
> That the property gets set, or the attribute?

Either is fine: an attribute string is mapped to a property by the element's attributeChangedCallback, and the property handles the string and (should) coerce it to a non-string, so if Preact sends a string to the property, that should be fine. But for some reason that the string handling is not happening. I'm thinking there's a possibility this version of Lume broke (JS properties no longer handling strings).

**Comment by rschristian** [comment]
Fair enough, just wanted to double check as some users do expect one or the other (or both) to be set.

It's certainly possible for this to be a Preact bug but we'd need a minimal reproduction as Lume seems to be quite big. Happy to help where I can if you need me though, feel free to ping. Good luck!

**Comment by trusktr** [comment]
> some users do expect one or the other (or both) to be set.

Yeah, although no a problem in my case, I do think this a valid thing for users to want. I [proposed to add a new test](https://github.com/webcomponents/custom-elements-everywhere/issues?q=is%3Aissue+is%3Aopen+2352) to custom-elements-everywhere to test that frameworks allow users to choose.



> Happy to help where I can if you need me though, feel free to ping. Good luck!

Thank you! Will keep digging. 👷 ⛏️

**Comment by rschristian** [comment]
> I do think this a valid thing for users to want.

I'm certainly all for it (or a variation of it) and I'd guess some other Preact members are too. JSX is a slow beast to change, sadly, it'll be hard to land a major syntax change. Would simplify a lot of our code though.

**Comment by trusktr** [comment]
[Pota's JSX](https://pota.quack.uy/props/attributes-properties#Namespace-To-Force-Props-Type) supports `attr:foo=""`, `prop:foo=""`, and `bool:foo=""`, which has the same parity with Lit's `foo=`, `.foo=`, and `?foo=`, allowing users to have total control over setting an attribute, setting a prop, or toggling a boolean attribute (adding/removing). The `attr:` syntax is valid in JSX, and Preact's `h` would just need to handle that string.

It turns out the issue is in Lume element: a while ago (more than year!) the JS setters stopped handling strings (React 19 will cause the issue to become apparent too). In other template systems like Solid JSX, `foo=""` sets an attribute while `foo={}` sets the JS property on custom elements (and in that case type checking keeps me sending in the correct non-string types). Not sure how I've been getting lucky in Svelte and Vue templates, but likely something similar with `foo=""` setting attributes, or else just pure luck I didn't use some specific attributes (because some other attributes work fine if they are strings even when they shouldn't be).

**Comment by rschristian** [comment]
> The attr: syntax is valid in JSX, and Preact's h would just need to handle that string.

Indeed, but Babel and some other transpilers will error upon that by default (if configurable at all -- not all are).

For Preact, we basically do `if (prop in domElement) domElement[prop] = value; else domElement.setAttr(prop, value)` with a few exceptions, in case that's useful to know.
