### ISSUE TITLE
Error when starting dev server

### ISSUE THREAD

**Issue by atikenny** [preactjs/preset-vite#121]
## Description
When using the command `vite`, I get the following error message:
```
Error: @preact/preset-vite tried to access @babel/code-frame, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

## Notes
Seems like there is a dependency on the `@babel/code-frame` package, but it is not declared in the package.json.
The reason that it doesn't cause issues in most cases is because `@babel/core` depends on this package, but this could lead to breaking in the future if that package decides to drop it as a dependency.

**Comment by rschristian** [comment]
> `@babel/core` depends on this package, but this could lead to breaking in the future if that package decides to drop it as a dependency.

This is incredibly stable and a non-issue (beyond your package manager, whichever it is, being needlessly strict).

You can submit a PR if you really want though
