### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useContext')

### ISSUE THREAD

**Issue by dolie** [preactjs/preset-vite#124]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
Hello, 

I'm not able to run Preact components using SWR, in a test environnement.
In dev/prod environnement Preact handles perfectly SWR, but not in test environnement.
When I launch the test, it returns the error :
`TypeError: Cannot read properties of null (reading 'useContext')`

**To Reproduce**

Barebone example : https://github.com/dolie/preact-swr-vitest-bug

1. `git clone git@github.com:dolie/preact-swr-vitest-bug.git`
2. `pnpm i`
3. `pnpm vitest`

**Expected behavior**
Preact handles SWR in a test environnement, as it is running in dev/prod environnement.

**Additional Context**

SWR
Vitest
MSW
Testing-library

<img width="684" alt="339088817-e5442f68-71b5-4754-bb6f-2daf198164ec-2" src="https://github.com/preactjs/preact/assets/18349922/4f6f7227-ba20-4516-82b9-20bfa65b2ea6">

**Comment by rschristian** [comment]
Vitest unfortunately has problems aliasing, this is something we've seen a few times.

Can't go looking for reference issues right now (on phone, will take a look later) but I'm sure you can pretty easily find them on the Vitest repo.

I think this is something Vitest needs to address, not us here.

**Comment by dolie** [comment]
Thank you for you fast answer !

Ok, so [I added `preact/compat` using pnpm aliases](https://github.com/dolie/preact-swr-vitest-bug/commit/b6255bfda7b6b9a9088cf13ebe7d554dd968f91d), but it throws a new error about `useSyncExternalStore` ?

<img width="700" alt="Capture d’écran 2024-06-17 à 17 26 06" src="https://github.com/preactjs/preset-vite/assets/18349922/2be64ba5-0ed7-4233-9cf5-35b4b09b3b8c">

**Comment by rschristian** [comment]
That error says you're loading multiple copies of Preact at once; hooks, in both Preact and React, require that the library is loaded as singleton (only once).

Probably the dual-package hazard: https://github.com/vitest-dev/vitest/issues/4365. Again, something that unfortunately needs to be addressed in Vitest (as far as I am aware).

**Comment by dolie** [comment]
Vitest team [found a workaround](https://github.com/vitest-dev/vitest/issues/5915#issuecomment-2179794149)😉
I updated the repo [with it](https://github.com/dolie/preact-swr-vitest-bug/commit/ac9d34bf1dd5b8037db0c2d7a1f7f2bcc162fda9).
Thank you for your help @rschristian @JoviDeCroock 🙏
