### ISSUE TITLE
hook-names causing SyntaxError

### ISSUE THREAD

**Issue by maxbeatty** [preactjs/preset-vite#17]
I'm having an issue where if a TypeScript file (.ts) imports a TypeScript JSX file (.tsx) an uncaught error occurs:

> Uncaught SyntaxError: The requested module '/src/components/index.tsx' does not provide an export named 'render'

I've narrowed it down through trial and error to the [hook-names](https://github.com/preactjs/preset-vite/blob/v2.1.0/src/hook-names.ts) plugin. If I comment it out, everything works fine.

`vite.config.ts`:

```ts
import preact from '@preact/preset-vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [preact()],
});
```

`index.ts`

```ts
import { render } from './components'

render(document.querySelector('#example'))
```

`components/index.tsx`

```ts
import { render as p } from 'preact';

function Example() { return <div /> }

export function render(element: Element): void {
  p(<Example />, element);
}
```

`index.html`

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/src/favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    <div id="example"></div>

    <script type="module" src="/src/index.ts"></script>
  </body>
</html>
```

```sh
npx vite
```

**Comment by marvinhagemeister** [comment]
I'm unable to reproduce the described error with the snippets provided. There is no error for me and vite compiles and serves the code as expected. Maybe there is something different in your setup?

**Comment by maxbeatty** [comment]
Thank you for taking the time to look into this!

I found the root cause. A `babel` config was in the same directory as `vite` for `jest` which caused `babel-plugin-transform-hook-names` to transform improperly. Moving the jest config to only target the test environment fixed the issue.

```diff
- module.exports = jestConfig
+ module.exports = {
+  env: {
+    test: jestConfig
+  }
+ }
```
