### ISSUE TITLE
"import not found" when using dev server

### ISSUE THREAD

**Issue by ntkoopman** [preactjs/preset-vite#19]
After upgrading to 2.1.0 I get 
```
SyntaxError: import not found Foo
```
when importing a `.tsx` file. The imported file is returned as a commonjs file instead of ESM.

Everything works correctly on 2.0.1 and in the production build.

**Comment by marvinhagemeister** [comment]
@ntkoopman Awesome, thanks a bunch for reporting it. Just released a new version with the fix.
