### ISSUE TITLE
[BUG]: I got error : Support for the experimental syntax 'decorators-legacy' isn't currently

### ISSUE THREAD

**Issue by Dushusir** [preactjs/preset-vite#27]
**error:**

Support for the experimental syntax 'decorators-legacy' isn't currently

**version:**

2.1.5

**check problem:**
use https://github.com/Dushusir/vite-ts-types

```bash
git clone https://github.com/Dushusir/vite-ts-types
cd vite-ts-types
npm i
npm i -g lerna
lerna bootstrap
npm run dev
```
then throw error

**Comment by Dushusir** [comment]
2.0.0 is fine

**Comment by marvinhagemeister** [comment]
Just checked with the latest version `2.1.7` of our preset and vite `2.8.4` and I can't reproduce the described issue. Supposedly this was either fixed upstream or when we switched over to transpile jsx via babel.
