### ISSUE TITLE
Decorators break application

### ISSUE THREAD

**Issue by darklight9811** [preactjs/preset-vite#43]
![image](https://user-images.githubusercontent.com/20667774/156480015-2d7d4b11-2c80-4cfd-a9a3-c8908c0f14c1.png)

Couldn't find a way to solve this within vite

**Comment by ps73** [comment]
This is now possible with the babel config option: https://github.com/preactjs/preset-vite#babel-configuration and the following:
```js
plugins: [
  ['@babel/plugin-proposal-decorators', { legacy: true }]
]
```

**Comment by JoviDeCroock** [comment]
Closing because of @ps73 fixing it! I think this feature is part of 2.2.0
