### ISSUE TITLE
preact-ts preset with react specific libraries

### ISSUE THREAD

**Issue by Geebrox** [preactjs/preset-vite#45]
### Bug description

I am using vite with preact-ts preset. Tried to install a react-specific library (chakra-ui). In development everything is okay, I can see chakra-ui components on the page, but when I am trying to build the project it fails with a lot of errors related to react import statement.

I tried to add aliases into vite.config.ts

```js
resolve: {
    alias: {
      react: 'preact/compat',
      'react-dom': 'preact/compat',
    },
  },
```

### Reproduction

https://github.com/Geebrox/vite-preact-chakra

### System Info

```shell
  System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 95.89 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.3 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.75
    Safari: 15.4
```

### Used Package Manager
- yarn

## Original issue:
https://github.com/vitejs/vite/issues/7662

**Comment by Shyam-Chen** [comment]
TypeScript preact/compat configuration

```json5
{
  "compilerOptions": {
    ...
    "skipLibCheck": true,
    "baseUrl": "./",
    "paths": {
      "react": ["./node_modules/preact/compat/"],
      "react-dom": ["./node_modules/preact/compat/"]
    }
  }
}
```

**Comment by rschristian** [comment]
Going to close this out as it looks unrelated to this plugin.
