### ISSUE TITLE
Support vite 3

### ISSUE THREAD

**Issue by IanVS** [preactjs/preset-vite#49]
Hi, I attempted to update a storybook vite example to vite 3 beta, and found that our preact example is failing.  

I've created a minimal reproduction at https://github.com/IanVS/vitejs-vite-ccuzee.

Besides the `peerDependencies` needing an update, I get an error when running a built app (dev works fine).  The error is:

```
Uncaught ReferenceError: require is not defined
```

Which comes from an attempted `require("preact")`.

**Comment by JoviDeCroock** [comment]
Odd, I would have assumed vite to use the `import` or `module` build which does not use require https://www.runpkg.com/?@preact/preset-vite@2.2.0/dist/esm/index.mjs

**Comment by IanVS** [comment]
This seems to be a duplicate of https://github.com/preactjs/preact/issues/3558.
