### ISSUE TITLE
warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module

### ISSUE THREAD

**Issue by akbr** [preactjs/preset-vite#60]
I started seeing [this issue](https://github.com/vitejs/vite/issues/8644) after updating vite just now.

```
[vite] hmr update /src/App.tsx
[vite] warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module
```

The config described [here](https://github.com/vitejs/vite/issues/8644#issuecomment-1159308803) silences the warning just fine. 

Perhaps this is something worth addressing in the preset library?

**Comment by sapphi-red** [comment]
The warning is removed in 0.14.46: https://github.com/evanw/esbuild/commit/0905d851eca6666bc606ff719450336ab868c547
So this won't happen in Vite 2.8+.

**Comment by rschristian** [comment]
Sounds like this can be closed out then.
