### ISSUE TITLE
Is there a way to get the Preact source instead of the minified version?

### ISSUE THREAD

**Issue by marlun78** [preactjs/preset-vite#64]
I have an issue with my app. When running in development mode (`vite`), it works great, but when switching over to production build (`vite build && vite preview`), I get an error: 

```
Uncaught (in promise) DOMException: Failed to execute 'createElement' on 'Document': 
  The tag name provided ('[object Object]') is not a valid name.
```

To make debugging easier, it would be great to be able to read the Preact source instead of the minified code.

**Comment by rschristian** [comment]
Directly use? No. But that's what the sourcemaps are there for. Should be able to do something like this to enable them in prod:

```js
// vite.config.js
export default {
  build: {
    sourcemap: true,
  },
}
