### ISSUE TITLE
preset-vite doesn't work with latest vite 4.0

### ISSUE THREAD

**Issue by pitis** [preactjs/preset-vite#70]
Hello, I tried to start a new project with vite 4.0, I selected the preact typescript template, but when I "npm install", it is unable to resolve dependency tree.

Could not resolve dependency:
npm ERR! peer vite@"2.x || 3.x" from @preact/preset-vite@2.4.0

It needs to be updated to support the latest vite.

Thank you!

**Comment by pitis** [comment]
@JoviDeCroock ok. thanks for letting me know, but why are those issues closed if the problem persists? I wouldn't have commented if I would have seen those in the "Issues" section already.

**Comment by JoviDeCroock** [comment]
Typically in GitHub and OSS workflows when the PR is merged the issue is closed as it will be part of the next release
