### ISSUE TITLE
Unable to use react-datetime library

### ISSUE THREAD

**Issue by disce-omnes** [preactjs/preset-vite#75]
**Problem**: when using [react-datetime](https://www.npmjs.com/package/react-datetime) library the resulting bundle fails to load in browser with an error `Failed to execute 'createElement' on 'Document': The tag name provided ('[object Module]') is not a valid name.`

With `preact/debug` the error changes to `Invalid type passed to createElement(): [object Module]`.

When starting dev-server with `npx vite` everything loads correctly.

The problem can be reproduced with the following setup:
`package.json`:
```json
"scripts": {
  "dev": "vite",
  "build": "vite build"
},
"dependencies": {
  "preact": "^10.13.2",
  "react-datetime": "^3.2.0"
},
"devDependencies": {
  "@preact/preset-vite": "^2.5.0",
  "vite": "^4.3.2"
}
```
`vite.config.js`:
```js
import { defineConfig } from "vite";
import preact from "@preact/preset-vite";

export default defineConfig({
  plugins: [preact()]
});
```
`index.jsx`:
```jsx
import "preact/debug";
import { render } from "preact/compat";
import Datetime from 'react-datetime';

function App() {
  return (
    <Datetime />
  );
}

render(<App />, document.getElementById("app"));
```
index.html:
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Document</title>
</head>

<body>
  <div id="app"></div>
  <script src="index.jsx" type="module"></script>
</body>

</html>
```

**Comment by marvinhagemeister** [comment]
Thanks for filing an issue. I took a stab at it and it seems to be an issue in `vite` itself. It seems to get the CommonJS to ESM conversion wrong for the default export of `react-datetime`. Instead of returning the component it returns `{ default: ... }` instead.

**Comment by marvinhagemeister** [comment]
Filed an issue over at the vite project https://github.com/vitejs/vite/issues/13009 . Let's move discussion there since it's a vite issue.

**Comment by disce-omnes** [comment]
Closing since it's a vite issue.

**Comment by disce-omnes** [comment]
Closing since it's a vite issue.
