### ISSUE TITLE
HMR not working when using react -> @preact/compat override in package.json

### ISSUE THREAD

**Issue by bhallstein** [preactjs/preset-vite#76]
**Edit:** _I initially thought it was a dynamic backend that was causing this issue, this turned out to be wrong. Skip to my next comment as what I wrote here turned out to be a red herring._

Our project uses a dynamic backend. I'm trying to switch it to use preact and `@preact/preset-vite` is looking like _almost_ a drop-in replacement, which is fairly amazing.

However, HMR isn't working. On https://vitejs.dev/guide/backend-integration.html for HMR with react we have this:

```For development, inject the following in your server's HTML template (substitute http://localhost:5173 with the local URL Vite is running at):

<!-- if development -->
<script type="module" src="http://localhost:5173/@vite/client"></script>
<script type="module" src="http://localhost:5173/main.js"></script>
...

Note if you are using React with @vitejs/plugin-react, you'll also need to add this before the above scripts, since the plugin is not able to modify the HTML you are serving:

html
<script type="module">
  import RefreshRuntime from 'http://localhost:5173/@react-refresh'
  RefreshRuntime.injectIntoGlobalHook(window)
  window.$RefreshReg$ = () => {}
  window.$RefreshSig$ = () => (type) => type
  window.__vite_plugin_react_preamble_installed__ = true
</script>
```

(When the above is included in our served HTML with this preset in use and react removed, it errors in the browser console, so I assume it is not to be included when using this preset, though I'm not entirely confident in that.)

This leads me to wonder if there is an equivalent piece of code that is missing from our dynamically served backend when using this preset?

**Comment by marvinhagemeister** [comment]
Thanks for filing an issue. Can you share code with which we can reproduce the issue? Happy to look into it.

**Comment by rschristian** [comment]
Ended up finally tracking this down, after being plagued by it myself.

It seems that Vite will only optimize directly referenced deps in user code, and for some reason, if `preact` isn't optimized, HMR goes a bit wonky (only in the top level, can be broken if you clear Vite's cache, etc). Adding an import from `preact` anywhere in your app would fix it, but alternatively, we can make sure in the preset that it's always optimized.
