### ISSUE TITLE
Feature: Add `compat` option to disable `preact/compat` aliases

### ISSUE THREAD

**Issue by rschristian** [preactjs/preset-vite#78]
Can be enabled by default, but would be nice to allow users to have a bit more control without having to splice the plugins returned by the preset.

I saw that [Astro ran into this as well](https://github.com/withastro/astro/pull/7924/files#r1282361746) so I think it would be a reasonable addition.

**Comment by matthewp** [comment]
Thanks @rschristian, I was going to open an issue as well. Having a `compat: false` or `noCompat: true` or whatever else would be nice.
